### ISSUE TITLE
XSL Transformation on sitemap?

### ISSUE THREAD

**Issue by ianfoxofficial** [uhaciogullari/SimpleMvcSitemap#10]
Is there a way to attach an XSLT template to the output? I can't find anything on that. Thnx.

**Comment by uhaciogullari** [comment]
Nope, not yet. We can try to create one if you want to work on it.

**Comment by Michu44** [comment]
Wold be really interested in a solution here.
Do you have any idea yet on how/where you want to implement it?

**Comment by uhaciogullari** [comment]
[XmlSerializer class](https://github.com/uhaciogullari/SimpleMvcSitemap/blob/master/src/SimpleMvcSitemap/XmlSerializer.cs) handles the serialization.

What's the purpose of XSLT transformation exactly? Do you intend the change to output? It's defined on the protocol already.

**Comment by ianfoxofficial** [comment]
The purpose was to show humans a prettier sitemap when they visit it.

In the meanwhile I've built a separate "Human Sitemap" instead with the titles of the pages and items which I link to in the pages.

**Comment by spartanier7777** [comment]
For me it would be nice if you can implement it.
As I understand its just a line which appears bellow the following:
`<?xml version="1.0" encoding="UTF-8"?>`.

This one would be needed:
`<?xml-stylesheet type="text/xsl" href="//www.icrossing.com/sitemap.xsl"?>`

Perhaps you need to adjust the namespaces according to:
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">`

Finally i think the should be nothing more than a property or something else where the url to the .xls can be set. If the property set we have a xls if not we don't.

**Comment by Michu44** [comment]
For the purpose I agree with @ianfoxofficial so it can be viewed easy as a human.
I would love to see the feature, so there would be no redundant code and a standard would be followed.

The implementation can be done similar to the approach @spartanier7777 suggested.

@uhaciogullari I think it would be nice to support it in your current version too, not only in ASP.NET Core, if that would be possible.

**Comment by uhaciogullari** [comment]
@Michu44 We can certainly implement it in the current version.

@spartanier7777 I can handle the namespaces but what would be the input? Just a list of stylesheet URLs? If you could create the models I can try to inject them like explained [here](http://stackoverflow.com/questions/1461029/possible-to-add-a-xslt-stylesheet-to-a-serialized-xml-document).

**Comment by spartanier7777** [comment]
@uhaciogullari in my opinion it's nothing more than a string (url). This url points to a controller action which returns the xls. This would be my idea of the implementation.

**Comment by uhaciogullari** [comment]
Ok. I'll work on this one. Let's see if I can add it without a breaking change.

**Comment by Michu44** [comment]
@uhaciogullari I agree with @spartanier7777, a simple string overload would already be enough.
When you need anything just hit me up.

**Comment by uhaciogullari** [comment]
Actually if you have an existing xml stylesheet, that will be useful.

**Comment by spartanier7777** [comment]
@uhaciogullari 

You can find an example here:
http://www.icrossing.com/sitemap.xml

the according xsl to it:

http://www.icrossing.com/sitemap.xsl

**Comment by Michu44** [comment]
I have not created one of my own yet, but maybe these might help you, I would be building on something like this at least.

https://yoast.com/xsl-stylesheet-xml-sitemap/

Or the one @spartanier7777 provided in his example above:
http://www.icrossing.com/sitemap.xml
http://www.icrossing.com/sitemap.xsl

**Comment by uhaciogullari** [comment]
I pushed a beta version of v3. It contains the support for XSL style sheets. Please try it and see if we are missing something.

[Package](https://www.nuget.org/packages/SimpleMvcSitemap/3.0.0-beta1)
[v3 Documentation](https://github.com/uhaciogullari/SimpleMvcSitemap/blob/v3/README.md#style-sheets)

**Comment by spartanier7777** [comment]
@uhaciogullari Tested and works!  Please create asap a release version, that we can deploy your package on our prod env.

thanks 👍

**Comment by uhaciogullari** [comment]
I pushed [v3](https://www.nuget.org/packages/SimpleMvcSitemap/).

Cheers
