### ISSUE TITLE
Reverse SiteMap Index File Development

### ISSUE THREAD

**Issue by fcuneyt** [uhaciogullari/SimpleMvcSitemap#11]
Hi,

Can u add an ability to reverse index file generation parametrically.

Thanks.

**Comment by uhaciogullari** [comment]
I also got your email about this but I didn't have time to respond to it yet. Do you think you require a change in the library to achieve your goal?  Couldn't it be handled by changing the ordering on your code?

Anyway it's possible to add this into ISitemapConfiguration. Do you think you can fork the repo and send a pull request?

**Comment by uhaciogullari** [comment]
I pushed a beta version of v3. It contains the support for reversing the order of sitemap index nodes. 
You need to set [this property ](https://github.com/uhaciogullari/SimpleMvcSitemap/blob/v3/src/SimpleMvcSitemap/SitemapIndexConfiguration.cs#L30)to true to make it work.


Please try it and see if we are missing something.

[Package](https://www.nuget.org/packages/SimpleMvcSitemap/3.0.0-beta1)
[v3 Documentation](https://github.com/uhaciogullari/SimpleMvcSitemap/blob/v3/README.md#style-sheets)

**Comment by uhaciogullari** [comment]
I pushed [v3](https://www.nuget.org/packages/SimpleMvcSitemap/).

Cheers
