### ISSUE TITLE
Sitemap LastMod property serialized in an incorrect format

### ISSUE THREAD

**Issue by geogauci** [uhaciogullari/SimpleMvcSitemap#16]
Google's webmasters tools is throwing several errors on the LastMod property, "An invalid date was found. Please fix the date or formatting before resubmitting". Upon inspection, as per [sitemaps.org](https://www.sitemaps.org/protocol.html), the date must be in a [W3C](https://www.w3.org/TR/NOTE-datetime) format.

I believe a minor update in SitemapNode.cs such as the following should do the trick (PS: not tested):
```
        /// <summary>
        /// Shows the date the URL was last modified, value is optional.
        /// </summary>
        [XmlElement("lastmod", Order = 2)]
        public string LastModificationDateW3C
        {
            get
            {
                if (this.LastModificationDate != null)
                {
                    return XmlConvert.ToString((DateTime)this.LastModificationDate);
                }
                return null;
            }
        }
```

```
        /// <summary>
        /// The date the URL was last modified
        /// </summary>
        public DateTime? LastModificationDate { get; set; }
```

**Comment by uhaciogullari** [comment]
Could you share an example datetime generated in your sitemap?

**Comment by geogauci** [comment]
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url>
                <loc>http://localhost:50999/main</loc>
                <lastmod>2017-01-18T12:10:01.087</lastmod>
                <changefreq>daily</changefreq>
        </url>
</urlset>
```

**Comment by uhaciogullari** [comment]
Ok, I'll take a look this one and try to provide a fix today.

**Comment by geogauci** [comment]
Thanks!

**Comment by uhaciogullari** [comment]
I see different behaviour on .NET and .NET Core.
Which one are you using?

**Comment by geogauci** [comment]
.Net (4.6.1)

**Comment by uhaciogullari** [comment]
Your approach's also generating a weird format.

You can take a look at this branch:
https://github.com/uhaciogullari/SimpleMvcSitemap/compare/datetime-format-fix?expand=1

**Comment by geogauci** [comment]
Possibly adding the serialization mode to the xml converter might help

![image](https://cloud.githubusercontent.com/assets/497732/22117094/fee99d90-de72-11e6-9678-52e6c545319b.png)

**Comment by uhaciogullari** [comment]
There are two other alternatives.

- [Convert your value to UTC](https://msdn.microsoft.com/en-us/library/system.datetime.touniversaltime(v=vs.110).aspx)
- Create your DateTime explicitly as Local like below if you want to use specify your timezone
`new DateTime(2016, 3, 3, 0, 0, 0, DateTimeKind.Local);`

Could you test this and see if it works?

**Comment by geogauci** [comment]
The first method (converting to UTC) does not work, however the second method [works perfectly](http://propjetaillum.com/sitemapforsale)! :)

Just a recap, after retrieving the datetime required, I created a new DateTime, as per your second suggestion, like so: 
```
        DateTime lta = <get some date, _in local time zone_ >
        DateTime w3cDateTime = new DateTime(lta.Year, lta.Month, lta.Day, lta.Hour, lta.Minute, lta.Second, DateTimeKind.Local);
        sitemapNode.LastModificationDate = w3cDateTime;
```

Thanks for your support and for your awesome tool! :)

**Comment by uhaciogullari** [comment]
You're welcome.

It seems like there is a [ToLocalTime](https://msdn.microsoft.com/en-us/library/system.datetime.tolocaltime(v=vs.110).aspx) method as well and it looks cleaner.
