### ISSUE TITLE
README.md error

### ISSUE THREAD

**Issue by kurtwendling** [uhaciogullari/SimpleMvcSitemap#17]
The code example under Sitemap Index Files has an error.
`return new SitemapProvider().CreateSitemap(new SitemapIndexModel(sitemapIndexNodes));`

should be:
`return new SitemapProvider().CreateSitemapIndex(new SitemapIndexModel(sitemapIndexNodes));`

**Comment by uhaciogullari** [comment]
Thanks for pointing that out. It's fixed now.
