### ISSUE TITLE
How To Return Result in UTF-8 Encoding 

### ISSUE THREAD

**Issue by ahmedabdellatiff** [uhaciogullari/SimpleMvcSitemap#21]
please how to set xml version and utf encoding in Result 

![err2](https://user-images.githubusercontent.com/9210813/29741050-6c5a66b8-8a65-11e7-9469-588eb8aeb1e2.PNG)
![erro](https://user-images.githubusercontent.com/9210813/29741051-6c5cd4d4-8a65-11e7-95f6-21b6c56c2211.PNG)

**Comment by uhaciogullari** [comment]
The XML output is  UTF8 encoded already. Setting the XML version is not
supported yet. Could you explain why you need it? Search engines don't care
about it AFAIK.
