### ISSUE TITLE
Translations make the sitemap not work

### ISSUE THREAD

**Issue by romias** [uhaciogullari/SimpleMvcSitemap#22]
Once I enter the translation collection to a SitemapNode, the generated sitemap is no longer a XML, it is just a string with concatenated urls

**Comment by uhaciogullari** [comment]
Hi @romias 

I think I get what you mean. We have to add "xmlns:xhtml" namespace when there is a translation node. Then the browser thinks it's HTML and it only displays the texts within the tags.

If you view the source in the browser, you will see that correct sitemap file is generated.
![translation](https://user-images.githubusercontent.com/1431130/30616560-e9ac3b60-9d92-11e7-89d8-13db8c6d889b.PNG)

**Comment by Racines** [comment]
The problem is still present. 
@uhaciogullari If I understand you correctly, the bug is only visual and google bot will be able to use the sitemap as expected?

**Comment by uhaciogullari** [comment]
The namespace is already added. View the source on your sitemap endpoint and you will see that correct XML is generated.

**Comment by Racines** [comment]
yes I used some sitemap validator, it seems to be ok, thanks
