### ISSUE TITLE
Output format of LastModificationDate is incorrect.

### ISSUE THREAD

**Issue by xiaoxin01** [uhaciogullari/SimpleMvcSitemap#24]
Hi,

I found that the lastmod format is like this:

```
<lastmod>2017-10-25T00:00:00</lastmod>
```

Google search console said this format is incorrect. The correct format need to be W3C Datetime. Witch can find here

    https://www.w3.org/TR/NOTE-datetime

The example date format:

1994-11-05T13:15:30Z

So need to add 'Z' at the end of output?

**Comment by uhaciogullari** [comment]
Hi @xiaoxin01 

This issue was [raised before](https://github.com/uhaciogullari/SimpleMvcSitemap/issues/16#issuecomment-273917903). You can easily fix it by converting the date to local date.
