### ISSUE TITLE
ASP.NET Core using .NET Framework use wrong dlls

### ISSUE THREAD

**Issue by glararan** [uhaciogullari/SimpleMvcSitemap#26]
Hi,

I downloaded version 3.1 using nuget. I have project ASP.Net Core v2 using .NET Framework 4.7. After including SimpleMvcSitemap I am getting error because **new SitemapProvider().CreateSitemap(new SitemapModel(nodes));** returns **System.Web.Mvc.ActionResult** instead of **Microsoft.AspNetCore.Mvc.IActionResult**.

I have to download source code for now and remove Mvc #ifs

**Comment by uhaciogullari** [comment]
So you are running ASP.NET MVC Core on .NET Framework. I hadn't thought about this use case before really. I would have to create a seperate package to support all the scenarios. I'll think of something in the weekend.

**Comment by glararan** [comment]
Yes like you said I am running ASP.NET Core on .NET Framework. If you create separate package let me know :) It would help

**Comment by uhaciogullari** [comment]
The library is only targeting netstandard1.6 by version 4. I don't know if this issue is still relevant for you but it could be great if you could check.

**Comment by glararan** [comment]
I rewrote project this year into .NET Core 3.1, closing :) thanks for support
