### ISSUE TITLE
multiple dynamic sitemap provider

### ISSUE THREAD

**Issue by Nazgaul** [uhaciogullari/SimpleMvcSitemap#31]
Let say i have multiple dynamic data i want to put in the sitemap ( let say multiple tables).
I created multiple SitemapIndexConfiguration for each type.
Is there a way i can merge them for SitemapIndexNode?
Can you provide an example if yes?

thanks.

**Comment by uhaciogullari** [comment]
I would just serve each of them from different endpoints and list them in a sitemap index file [like explained here](https://github.com/uhaciogullari/SimpleMvcSitemap#sitemap-index-files). I guess the index files can refer to other index files. Let me know if it works.

**Comment by uhaciogullari** [comment]
Does the ../product-sitemap/ serve the index file for the products? Then you could create a sitemap index file with this list:

.../product-sitemap
.../buyer-sitemap/
etc.

**Comment by Nazgaul** [comment]
IF you mean create sitemap index inside sitemap index. then accourding to [this](https://webmasters.stackexchange.com/questions/18243/can-a-sitemap-index-contain-other-sitemap-indexes) - you can't

**Comment by uhaciogullari** [comment]
I didn't know that wasn't allowed. I think the easiest way is to keep multiple index files and submit them all to Google.
