### ISSUE TITLE
How to add odd, urls to sitemap when using Dynamic Sitemap Index method

### ISSUE THREAD

**Issue by hades200082** [uhaciogullari/SimpleMvcSitemap#33]
We have a large number of CMS driven URL's that we're using the Dynamic Sitemap Index method to generate the sitemaps for.

We also have a handful of additional URLs that are only present in the MVC app and we need to also include these in the sitemap. 

Is there an example of how to add these extra URLs in when using the dynamic method?

**Comment by uhaciogullari** [comment]
No, it's not supported out of the box. Take a look at [DynamicSitemapIndexProvider](https://github.com/uhaciogullari/SimpleMvcSitemap/blob/master/src/SimpleMvcSitemap/DynamicSitemapIndexProvider.cs). You can tweak it to include another sitemap index node if the extra links are static. Otherwise you have to come up with an implementation that can use multiple data sources.

**Comment by hades200082** [comment]
It would still be helpful to be able to, at least, insert additional sitemaps into the sitemap index that's generated dynamically.

When working with headless CMS in particular the CMS content can be used to generate a dynamic sitemap/index using `DynamicSitemapIndexProvider` but there will always be odds and ends pages that are only present in the MVC application and don't appear in the CMS at all.

Being able to add these additional pages so that all pages are accounted for within the sitemap (and in particular the sitemap index paging calculations) would be extremely useful and much neater than having a separate sitemap with only a handful of pages in it next to a sitemap index that might lead to 100k's of pages on a large site.

**Comment by uhaciogullari** [comment]
I can provide a way to add static sitemap nodes to your sitemap index file. However DynamicSitemapIndexProvider can also generate a sitemap in cause you return less than 50k items from your query. Then it wouldn't be possible to add sitemap nodes there. What do you think about that?

**Comment by hades200082** [comment]
When using DynamicSitemapIndexProvider, just having a way to pass in multiple IQueryables would likely be enough... that way you might have multiple sections plus a basic `List<>()` of the odd ones

**Comment by uhaciogullari** [comment]
I don't think there is a clean way query multiple IQueryables in the library. The paging code will be a mess. I think it's better that you provide your own implementation in your own code.

**Comment by hades200082** [comment]
Could it not be passed as a params array that you then loop through?

**Comment by uhaciogullari** [comment]
As far as I'm concerned, no. You are free to write your implementation. I'm going to close this issue.
