### ISSUE TITLE
Can add more than one video to a URL, google allows more than one.

### ISSUE THREAD

**Issue by ali-almosawi** [uhaciogullari/SimpleMvcSitemap#34]
How to add more than one Video to a url.

**Comment by uhaciogullari** [comment]
It's not supported right now. I'll have to fix it.

**Comment by SPWwj** [comment]
not working well on large sitemap.
SimpleMvcSitemap work fine when sitemap contain only 50+ urls.
However when trying generate large amount of urls e.g 1000+ or 50000
i got errors like this "error on line 1 at column 65697: Opening and ending tag mismatch: lastmourl line 0 and url"

**Comment by uhaciogullari** [comment]
Fixed! You can get the new version.
