### ISSUE TITLE
Wrong datetime output format?

### ISSUE THREAD

**Issue by skydiverMN** [uhaciogullari/SimpleMvcSitemap#40]
When having Google crawl the sitemap.xml which lives at my domain's root, I get back invalid date for each entry.  

This is what I'm creating, but is this a valid date?
<lastmod>2019-10-16T09:56:15.9800168Z</lastmod>

If not, how can I modify it to something that's acceptable?

**Comment by uhaciogullari** [comment]
https://github.com/uhaciogullari/SimpleMvcSitemap/issues/16#issuecomment-274034770

**Comment by skydiverMN** [comment]
Thank you!

Richie

**Comment by uhaciogullari** [comment]
You're welcome. I added a note to readme, hope it doesn't bite anyone else again :)
