### ISSUE TITLE
Missing await in ExecuteResultAsync of XmlResult

### ISSUE THREAD

**Issue by wojcichy** [uhaciogullari/SimpleMvcSitemap#41]
This line should be awaited:
https://github.com/uhaciogullari/SimpleMvcSitemap/blob/02198ace4864cef9b08ae721bda82640f38d3d7e/src/SimpleMvcSitemap/XmlResult.cs#L47

I had some cases, where only a part of a sitemap was returned in a http response, because the task had not completed. Everything started working well after making this method async and awaiting all internal async calls.

**Comment by uhaciogullari** [comment]
Thanks for finding this. It was the same issue in #39 very probably. I pushed a new version to NuGet.
