### ISSUE TITLE
Not generating xsi:schemaLocation= or xmlns= attributes!

### ISSUE THREAD

**Issue by FrancescoBonizzi** [uhaciogullari/SimpleMvcSitemap#47]
Hi! Thanks for your very useful tool, but I have a little problem!

My sitemap gets generated without any attributes on the url element. [You can see it here](https://www.imaginesoftware.it/sitemap.xml) generated in real time.

The cose I used:

```
[Route(template: "sitemap.xml")]
public IActionResult SitemapXml()
{
    var routes = _routesInspector.AllRoutes;
    var nodes = new List<SitemapNode>();
    foreach (var section in routes)
    {
        foreach (var route in section.Value)
        {
            nodes.Add(new SitemapNode(Url.Content(route.Url)));
        }
    }

    return new SitemapProvider().CreateSitemap(new SitemapModel(nodes));
}
```

Do I missed something? 
I noticed it because Google Search Console says it cannot read it!

Thanks.

**Comment by uhaciogullari** [comment]
Hi Francesco

What attributes are you missing? You can specify the optional attributes like described [here](https://github.com/uhaciogullari/SimpleMvcSitemap#examples). Your link doesn't work but the sitemap on https://www.imaginesoftware.it/sitemap.xml looks valid to me.

**Comment by FrancescoBonizzi** [comment]
Hi and thanks for answering.
I fixed the link. I think I'm a little stupid as I noticed that Firefox has an integrated viewer that removed the attribute.

Thanks!
