### ISSUE TITLE
Issue with date format in google.

### ISSUE THREAD

**Issue by mvpssii** [uhaciogullari/SimpleMvcSitemap#7]
Google dont like the date format.
<lastmod>2016-03-16T17:21:09.465+01:00</lastmod>

https://support.google.com/news/publisher/answer/74288?hlrm=en

**Comment by uhaciogullari** [comment]
It looks like they support this format too:

> Complete date plus hours, minutes, seconds and a decimal fraction of a second
> YYYY-MM-DDThh:mm:ss.sTZD (e.g., 1997-07-16T19:20:30.45+01:00)

Is there something that I am missing?

**Comment by mvpssii** [comment]
If I set :
SitemapNode.LastModificationDate = now
The return on sitemap is correct : <lastmod>2016-03-18T01:23:32+01:00</lastmod>
But is I set SitemapNode.LastModificationDate = New date(2016,3,3)
The return is incorrect for google : <lastmod>2016-03-15T00:00:00</lastmod>
I need set : LastModificationDate = Now.ToString("yyyy-MM-ddThh:mm:sszzz")
To good result.



De : Ufuk Hacıoğulları [mailto:notifications@github.com]
Envoyé : jeudi 17 mars 2016 07:53
À : uhaciogullari/SimpleMvcSitemap <SimpleMvcSitemap@noreply.github.com>
Cc : Avenir Numérique <info@mvp-ssii.com>
Objet : Re: [SimpleMvcSitemap] Issue with date format in google. (#7)


It looks like they support this format too:

Complete date plus hours, minutes, seconds and a decimal fraction of a second
YYYY-MM-DDThh:mm:ss.sTZD (e.g., 1997-07-16T19:20:30.45+01:00)

Is there something that I am missing?

**Comment by uhaciogullari** [comment]
I think it's still valid in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators). You are creating the DateTime instance without any timezone info so the XML serializer can't output any timezone.

This should create an instance with timezone:

    new DateTime(2016, 3, 3, 0, 0, 0, DateTimeKind.Local);

**Comment by uhaciogullari** [comment]
Hi mvpssii,

Can I close this one?

**Comment by mvpssii** [comment]
Hi,
yes

De : Ufuk Hacıoğulları [mailto:notifications@github.com]
Envoyé : lundi 28 mars 2016 10:35
À : uhaciogullari/SimpleMvcSitemap <SimpleMvcSitemap@noreply.github.com>
Cc : Avenir Numérique <info@mvp-ssii.com>
Objet : Re: [SimpleMvcSitemap] Issue with date format in google. (#7)


Hi mvpssii,

Can I close this one?
